name: adept_drive
description: Adept drive mobile app.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_downloader: ^1.8.3+2
  flutter_svg: ^1.1.4
  get: ^4.6.5
  google_fonts: ^3.0.1
  lottie: ^1.4.2
  path_provider: ^2.0.11
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
