name: adept_drive
description: Adept drive mobile app.

publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_downloader: ^1.8.4
  flutter_svg: ^1.1.4
  get: ^4.6.5
  google_fonts: ^3.0.1
  lottie: ^1.4.2
  path_provider: ^2.0.11
  permission_handler: ^10.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/one_drive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
